import React from 'react'
const ManageContext = React.createContext({
    files: [],
    pending: false,
    allSongs: [],
    blogs:[],
    images:[],
    createData: {},
    updateData: {},
    updateBlogData: {},
    createBlogData: {},
    createBlogErrors: {},
    updateBlogErrors: {},
    createDataErrors: {},
    updateDataErrors: {},
    handleCreateDataChange: ()=>{},
    handleUpdateDataChange: ()=>{},
    handleCreateFileChange: ()=>{},
    handleUpdateFileChange: ()=>{},
    handleFilesChange: ()=>{},
    deleteImage: ()=>{},
    getBlog: ()=>{},
    deleteBlog: ()=>{},
    deleteSong: ()=>{},
    handleFilesSubmit: ()=>{},
    handleCreateSubmit: ()=>{},
    handleCreateBlogDataChange: ()=>{},
    handleUpdateBlogDataChange: ()=>{},
    handleCreateBlogSubmit: ()=>{},
    handleUpdateBlogSubmit: ()=>{},
    handleUpdateSubmit: ()=>{}  
})
export default ManageContext